import type { Metadata } from "next";
import { Faustina } from "next/font/google";
import "./globals.css";

const faustina = Faustina({
  variable: "--font-faustina",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Study Sesh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${faustina.variable} antialiased`}>{children}</body>
    </html>
  );
}
